### ISSUE TITLE
Stacks

### ISSUE THREAD

**Issue by horerick46** [Anisha7860/Hacktoberfest#16]
add folder-related stack and its operation.

**Comment by horerick46** [comment]
please assign it to me and please add hacktober22 tag to it

**Comment by Anisha7860** [comment]
Okay done , go ahead

**Comment by horerick46** [comment]
mam I requested for the pull request you can merge it.

**Comment by horerick46** [comment]
mam hacktober is not accepting the pull request
![hact](https://user-images.githubusercontent.com/79391039/193648037-a04f01cf-12a9-4182-9c81-be1e3357f358.JPG)

**Comment by Anisha7860** [comment]
Check again after few mins

**Comment by horerick46** [comment]
ok
can I add queue also??? as an issue??

**Comment by horerick46** [comment]
ok
can I add queue also??? as an issue??

**Comment by Anisha7860** [comment]
Don't create issues, add it directly in a new folder and send pr

**Comment by horerick46** [comment]
the hacktober tag??

**Comment by horerick46** [comment]
will it make hactober eligible

**Comment by Anisha7860** [comment]
I can add tht while merging it

**Comment by horerick46** [comment]
@Anisha7860  the queue folder is also added.

**Comment by horerick46** [comment]
the new merge request is also not visible on hacktober page as well the old merge one isn't still updated it still is excluded.

**Comment by horerick46** [comment]
@Anisha7860  the pull requests are showing  excluded
![hack2](https://user-images.githubusercontent.com/79391039/193740564-e5818870-8e40-40db-bae1-4e3b98008a50.JPG)

**Comment by horerick46** [comment]
please mam help me out

**Comment by Anisha7860** [comment]
You can contribute on some other repository and check .
